[package]
name = "rs"
version = "0.1.0"
authors = ["James Gowans <jgowans@amazon.com>"]
edition = "2018"

[[bin]]
name = "sender"

[[bin]]
name = "receiver"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
